# Generated by Django 3.0.6 on 2020-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, max_length=3, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city_or_village', models.CharField(max_length=100)),
                ('PIN_code', models.IntegerField(max_length=6)),
                ('aadhaar_no', models.IntegerField(blank=True, max_length=12, null=True)),
                ('pan_no', models.EmailField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, max_length=3, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city_or_village', models.CharField(max_length=100)),
                ('PIN_code', models.IntegerField(max_length=6)),
                ('aadhaar_no', models.IntegerField(blank=True, max_length=12, null=True)),
                ('pan_no', models.EmailField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
