# Generated by Django 3.0.6 on 2020-05-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='PIN_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='find',
            name='aadhaar_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='pan_no',
            field=models.EmailField(blank=True, default=0, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='PIN_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lost',
            name='aadhaar_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='pan_no',
            field=models.EmailField(blank=True, default=0, max_length=254, null=True),
        ),
    ]
