# Generated by Django 3.0.6 on 2020-06-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaF', '0003_auto_20200529_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='find',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='pan_no',
        ),
    ]
