# Generated by Django 3.0.6 on 2020-06-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaF', '0007_auto_20200602_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='lose',
            name='city_or_village',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lose',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lose',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
