# Generated by Django 3.0.6 on 2020-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaF', '0008_auto_20200602_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='lose',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lose',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
