# Generated by Django 3.0.6 on 2020-06-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaF', '0012_auto_20200603_0049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='man',
        ),
    ]
