# Generated by Django 3.0.6 on 2020-06-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaF', '0013_delete_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='age',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
