# Generated by Django 3.0.6 on 2020-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaF', '0019_auto_20200614_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='PIN_code',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='aadhaar_no',
            field=models.PositiveIntegerField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
