# Generated by Django 3.0.6 on 2020-06-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaF', '0020_auto_20200614_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='PIN_code',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='aadhaar_no',
            field=models.IntegerField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='mobile_no',
            field=models.ImageField(max_length=10, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lost',
            name='mobile_no',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
