# Generated by Django 3.0.6 on 2020-06-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaF', '0022_auto_20200615_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='PIN_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='aadhaar_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='PIN_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='aadhaar_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
    ]
