# Generated by Django 3.0.6 on 2020-07-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaF', '0023_auto_20200616_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='PIN_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='aadhaar_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='age',
            field=models.CharField(blank=True, choices=[('Select Age', 'Select Age'), ('0-5', '0-5'), ('6-10', '6-10'), ('10-15', '10-15'), ('16-20', '16-20'), ('21-25', '21-25'), ('26-30', '26-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('41-45', '46-50'), ('51-55', '51-55'), ('56-60', '56-60'), ('61-65', '61-65'), ('66-70', '66-70'), ('71-75', '71-75'), ('76-80', '76-80'), ('81-85', '81-85'), ('86-90', '86-90')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='age',
            field=models.CharField(choices=[('Select Age', 'Select Age'), ('0-5', '0-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('21-25', '21-25'), ('26-30', '26-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('41-45', '46-50'), ('51-55', '51-55'), ('56-60', '56-60'), ('61-65', '61-65'), ('66-70', '66-70'), ('71-75', '71-75'), ('76-80', '76-80'), ('81-85', '81-85'), ('86-90', '86-90')], max_length=15),
        ),
    ]
